# Generated by Django 3.2.11 on 2022-01-19 09:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('rating', models.DecimalField(decimal_places=4, max_digits=6)),
                ('link', models.URLField()),
                ('place', models.IntegerField()),
                ('year', models.IntegerField()),
                ('imagen', models.URLField()),
                ('cast', models.CharField(help_text='Introduzca nombres separados por comas', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PelisIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduccion', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
