# Generated by Django 3.2.11 on 2022-02-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='generos',
            field=models.ManyToManyField(to='pelis.Genre'),
        ),
    ]
