# Generated by Django 3.2.11 on 2022-02-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0004_alter_genre_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
